a = input('Digite algo:')
print('O tipo primitivo desse valor é:',type(a))
print('Só tem espaços?',a.isspace())
print('é númerico:', a.isnumeric())
print('é alfabetico?', a.isalpha())
print('é alfanumerico?', a.isalnum())
print('esta em maiusculo?', a.isupper())
print('esta em minusculo?', a.islower())
print('esta capitalizado?', a.istitle())